apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-authorization-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-authorization
  template:
    metadata:
      labels:
        app: mysql-authorization
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: bookstack
            - name: MYSQL_DATABASE
              value: authorization
          ports:
            - containerPort: 3306
