apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: auth-server-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - name: auth-server
          image: auth-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9090
